
-- No type = MEADOW
-- No size = SMALL

POI_RANDOM_PLACEHOLDER = 1
POI_TEST = 99

-- MEADOW
POI_CRASHSITE_AREA = 101 --predefined area
POI_HIDEOUT_XL = 102
POI_MEADOW_GROWLAB_SILODISTRICT_XL = 103 -- minidungeon 2
POI_RUINCITY_XL = 104
POI_CRASHEDSHIP_LARGE = 105 -- other ship
POI_CAMP_LARGE = 106
POI_BUNK_BURIAL_QUEST_MEDIUM = 107
POI_LABYRINTH_MEDIUM = 108
POI_MECHANICSTATION_MEDIUM = 109
POI_PACKINGSTATIONVEG_MEDIUM = 110
POI_PACKINGSTATIONFRUIT_MEDIUM = 111
POI_WAREHOUSE2_LARGE = 112 -- 2 floors
POI_WAREHOUSE3_LARGE = 113 -- 3 floors
POI_WAREHOUSE4_LARGE = 114 -- 4 floors
POI_ROAD_KIOSK = 115
POI_CAMP = 116
POI_RUIN = 117
POI_RANDOM = 118
POI_FARMINGPATCH = 119 -- meadow adjacent to field
POI_RUIN_MEDIUM = 120
POI_CHEMLAKE_MEDIUM = 121
POI_RANDOM_MEDIUM = 122
--------------------------------
POI_WAREHOUSE4_QUEST_LARGE = 123
POI_MECHANICSTATION_QUEST_MEDIUM = 124
POI_BUILDERQUEST_RESOURCECAR = 125
POI_BUILDERQUEST_WOCHOUSE = 126 -- EASY 1
POI_BUILDERQUEST_CARDBOARDPOOP = 127 -- EASY 2
POI_BUILDERQUEST_XYLOPHONE = 128 -- EASY 6
POI_BUILDERQUEST_BEESUIT = 129 -- EASY 7
POI_BUILDERQUEST_CAROUSEL = 130  -- MEDIUM 2
POI_BUILDERQUEST_CROWBAR = 131  -- MEDIUM 4
POI_BUILDERQUEST_COMPASS = 132  -- MEDIUM 5
POI_BUILDERQUEST_NICEHOUSE_MEDIUM = 133 -- HARD 1
POI_BUILDERQUEST_STEELBRIDGE_MEDIUM = 134 -- HARD 3
POI_BUILDERQUEST_SLEDGEHAMMER_MEDIUM = 135 -- HARD 2
POI_BUILDERQUEST_BAGUETTE_MEDIUM = 136 -- HARD 4
POI_MEADOW_GROWLAB_QUEST_LARGE = 137 -- minidungeon 1
POI_SERVICE_ELEVATOR = 138
POI_EXCAVATION_BRIDGE = 139
POI_ROAD_RANDOM = 140
POI_ROAD_SCHEMATICSTATION = 141
POI_ROAD_CHEMPOOL = 142


-- FOREST
POI_FOREST_CAMP = 201
POI_FOREST_RUIN = 202
POI_FOREST_RANDOM = 203
POI_FOREST_RUIN_MEDIUM = 204
--------------------------------
POI_FOREST_BUILDERQUEST_SAWBLADEARM = 205 -- MEDIUM 7
POI_FOREST_GROWLAB_STATION_LARGE = 206 -- minidungeon 4
POI_FOREST_RANDOM_MEDIUM = 207


-- DESERT
POI_DESERT_RANDOM = 301
--------------------------------
POI_DESERT_BUILDERQUEST_BIGFAN = 302 -- MEDIUM 1
POI_DESERT_BUILDERQUEST_GARDEN = 303 -- MEDIUM 6
POI_DESERT_GROWLAB_CLIFFTOP_LARGE = 304 -- minidungeon 7
POI_DESERT_OILPOOL = 305
POI_OILLAKE_MEDIUM = 306


-- FIELD
POI_FIELD_RUIN = 401
POI_FIELD_RANDOM = 402
--------------------------------
POI_FIELD_BUILDERQUEST_CORNHEART = 403 -- EASY 4
POI_FIELD_BUILDERQUEST_COZYBED = 404 -- EASY 5


-- BURNTFOREST
POI_BURNTFOREST_FARMBOTSCRAPYARD_LARGE = 501
POI_BURNTFOREST_CAMP = 502
POI_BURNTFOREST_RUIN = 503
POI_BURNTFOREST_RANDOM = 504 -- No longer used
--------------------------------
POI_BURNTFOREST_BUILDERQUEST_TOTEBOTKEY = 505 -- EASY 3
POI_BURNTFOREST_BUILDERQUEST_CATAPULT_MEDIUM = 506 -- MEDIUM 3
POI_BURNTFOREST_GROWLAB_FROZEN_LARGE = 507 -- minidungeon 3


-- AUTUMNFOREST
POI_AUTUMNFOREST_CAMP = 601
POI_AUTUMNFOREST_RUIN = 602
POI_AUTUMNFOREST_RANDOM = 603 -- No longer used
--------------------------------
POI_AUTUMNFOREST_CLEARRUINSQUEST_MEDIUM = 604
POI_AUTUMNFOREST_BUILDERQUEST_POPCORN = 605 -- MEDIUM 8
POI_AUTUMNFOREST_BUILDERQUEST_MUSICBOX_MEDIUM = 606 -- MEDIUM 9


-- LAKE
POI_LAKE_RANDOM = 801
POI_LAKE_RANDOM_MEDIUM = 802
--------------------------------
POI_LAKE_GROWLAB_ISLAND_XL = 803 -- minidungeon 5
POI_EXCAVATION = 804
POI_LAKE_RUIN_MEDIUM = 805
